In [1]:
import pandas as pd

In [2]:
df_train = pd.read_csv("./train.csv")

In [4]:
df_train.loan_status.unique()

array([0, 1], dtype=int64)

In [5]:
df1 = df_train[df_train.loan_status == 1]

In [6]:
df1.to_csv('./loan_approved_data.csv')

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
11,11,22,33000,RENT,6.0,PERSONAL,B,10000,11.12,0.30,N,2,1
24,24,22,30000,RENT,3.0,MEDICAL,D,5000,16.49,0.17,N,4,1
25,25,25,25000,RENT,3.0,VENTURE,C,3500,13.49,0.14,Y,3,1
38,38,30,54000,RENT,0.0,MEDICAL,B,12500,11.71,0.24,N,10,1
39,39,22,32000,RENT,6.0,EDUCATION,D,8000,15.58,0.25,N,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58632,58632,23,29654,RENT,1.0,VENTURE,A,10000,6.54,0.34,N,2,1
58635,58635,32,69000,RENT,0.0,DEBTCONSOLIDATION,B,12000,10.20,0.17,N,7,1
58638,58638,29,46610,MORTGAGE,1.0,PERSONAL,D,2600,17.58,0.05,N,6,1
58641,58641,28,28800,RENT,0.0,MEDICAL,C,10000,12.73,0.35,N,8,1
58642,58642,23,44000,RENT,7.0,EDUCATION,D,6800,16.00,0.15,N,2,1

In [8]:
df2 = df_train[df_train.loan_status == 0]
df2.to_csv('./loan_rejected_data.csv')

In [9]:
df2

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58637,58637,24,75000,RENT,8.0,VENTURE,B,4000,10.75,0.05,N,4,0
58639,58639,22,70000,RENT,6.0,DEBTCONSOLIDATION,A,10000,7.29,0.14,N,4,0
58640,58640,34,120000,MORTGAGE,5.0,EDUCATION,D,25000,15.95,0.21,Y,10,0
58643,58643,22,30000,RENT,2.0,EDUCATION,A,5000,8.90,0.17,N,3,0
58644,58644,31,75000,MORTGAGE,2.0,VENTURE,B,15000,11.11,0.20,N,5,0

In [11]:
df1.dtypes

id                              int64
person_age                      int64
person_income                   int64
person_home_ownership          object
person_emp_length             float64
loan_intent                    object
loan_grade                     object
loan_amnt                       int64
loan_int_rate                 float64
loan_percent_income           float64
cb_person_default_on_file      object
cb_person_cred_hist_length      int64
loan_status                     int64
dtype: object

In [12]:
df2.columns

Index(['id', 'person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income', 'cb_person_default_on_file',
       'cb_person_cred_hist_length', 'loan_status'],
      dtype='object')

In [14]:
cols = []
for i in df2.columns:
    if df2[i].dtypes == 'int64' or df2[i].dtypes == 'float64':
        cols.append(i)

In [ ]:
df_train[cols].corr()['loan_status'] # feature selection +- 0.7 to 1

id                           -0.008138
person_age                   -0.001130
person_income                -0.169956
person_emp_length            -0.100428
loan_amnt                     0.144982
loan_int_rate                 0.338948
loan_percent_income           0.378280
cb_person_cred_hist_length   -0.003030
loan_status                   1.000000
Name: loan_status, dtype: float64

In [21]:
df_train.describe()

,id,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,loan_status
count,58645.000000,58645.000000,5.864500e+04,58645.000000,58645.000000,58645.000000,58645.000000,58645.000000,58645.000000
mean,29322.000000,27.550857,6.404617e+04,4.701015,9217.556518,10.677874,0.159238,5.813556,0.142382
std,16929.497605,6.033216,3.793111e+04,3.959784,5563.807384,3.034697,0.091692,4.029196,0.349445
min,0.000000,20.000000,4.200000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,0.000000
25%,14661.000000,23.000000,4.200000e+04,2.000000,5000.000000,7.880000,0.090000,3.000000,0.000000
50%,29322.000000,26.000000,5.800000e+04,4.000000,8000.000000,10.750000,0.140000,4.000000,0.000000
75%,43983.000000,30.000000,7.560000e+04,7.000000,12000.000000,12.990000,0.210000,8.000000,0.000000
max,58644.000000,123.000000,1.900000e+06,123.000000,35000.000000,23.220000,0.830000,30.000000,1.000000

In [ ]:
1